package mds.servicii;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-30T22:10:33.597+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://servicii.mds", name = "ElectricitatePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ElectricitatePortType {

    @WebMethod(action = "urn:putere")
    @Action(input = "urn:putere", output = "urn:putereResponse")
    @RequestWrapper(localName = "putere", targetNamespace = "http://servicii.mds", className = "mds.servicii.Putere")
    @ResponseWrapper(localName = "putereResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.PutereResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double putere(
        @WebParam(name = "u", targetNamespace = "http://servicii.mds")
        double u,
        @WebParam(name = "i", targetNamespace = "http://servicii.mds")
        double i
    );

    @WebMethod(action = "urn:rezistenta")
    @Action(input = "urn:rezistenta", output = "urn:rezistentaResponse")
    @RequestWrapper(localName = "rezistenta", targetNamespace = "http://servicii.mds", className = "mds.servicii.Rezistenta")
    @ResponseWrapper(localName = "rezistentaResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.RezistentaResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double rezistenta(
        @WebParam(name = "u", targetNamespace = "http://servicii.mds")
        double u,
        @WebParam(name = "i", targetNamespace = "http://servicii.mds")
        double i
    );

    @WebMethod(action = "urn:tensiune")
    @Action(input = "urn:tensiune", output = "urn:tensiuneResponse")
    @RequestWrapper(localName = "tensiune", targetNamespace = "http://servicii.mds", className = "mds.servicii.Tensiune")
    @ResponseWrapper(localName = "tensiuneResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.TensiuneResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double tensiune(
        @WebParam(name = "l", targetNamespace = "http://servicii.mds")
        double l,
        @WebParam(name = "q", targetNamespace = "http://servicii.mds")
        double q
    );
}
