package mds.servicii;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-30T20:22:33.997+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://servicii.mds", name = "MecanicaPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MecanicaPortType {

    @WebMethod(action = "urn:getLucruMecanic")
    @Action(input = "urn:getLucruMecanic", output = "urn:getLucruMecanicResponse")
    @RequestWrapper(localName = "getLucruMecanic", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetLucruMecanic")
    @ResponseWrapper(localName = "getLucruMecanicResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetLucruMecanicResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double getLucruMecanic(
        @WebParam(name = "forta", targetNamespace = "http://servicii.mds")
        double forta,
        @WebParam(name = "dist", targetNamespace = "http://servicii.mds")
        double dist,
        @WebParam(name = "x", targetNamespace = "http://servicii.mds")
        double x
    );

    @WebMethod(action = "urn:getFortaElastica")
    @Action(input = "urn:getFortaElastica", output = "urn:getFortaElasticaResponse")
    @RequestWrapper(localName = "getFortaElastica", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetFortaElastica")
    @ResponseWrapper(localName = "getFortaElasticaResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetFortaElasticaResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double getFortaElastica(
        @WebParam(name = "k", targetNamespace = "http://servicii.mds")
        double k,
        @WebParam(name = "x", targetNamespace = "http://servicii.mds")
        double x
    );

    @WebMethod(action = "urn:getForta")
    @Action(input = "urn:getForta", output = "urn:getFortaResponse")
    @RequestWrapper(localName = "getForta", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetForta")
    @ResponseWrapper(localName = "getFortaResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetFortaResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double getForta(
        @WebParam(name = "masa", targetNamespace = "http://servicii.mds")
        double masa,
        @WebParam(name = "acc", targetNamespace = "http://servicii.mds")
        double acc
    );

    @WebMethod(action = "urn:getFortaFrecare")
    @Action(input = "urn:getFortaFrecare", output = "urn:getFortaFrecareResponse")
    @RequestWrapper(localName = "getFortaFrecare", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetFortaFrecare")
    @ResponseWrapper(localName = "getFortaFrecareResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.GetFortaFrecareResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double getFortaFrecare(
        @WebParam(name = "miu", targetNamespace = "http://servicii.mds")
        double miu,
        @WebParam(name = "masa", targetNamespace = "http://servicii.mds")
        double masa,
        @WebParam(name = "g", targetNamespace = "http://servicii.mds")
        double g
    );
}
