package mds.servicii;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-30T20:22:34.031+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "Mecanica", 
                  wsdlLocation = "http://localhost:8081/fizicianWS/services/Mecanica?wsdl",
                  targetNamespace = "http://servicii.mds") 
public class Mecanica extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicii.mds", "Mecanica");
    public final static QName MecanicaHttpSoap11Endpoint = new QName("http://servicii.mds", "MecanicaHttpSoap11Endpoint");
    public final static QName MecanicaHttpEndpoint = new QName("http://servicii.mds", "MecanicaHttpEndpoint");
    public final static QName MecanicaHttpSoap12Endpoint = new QName("http://servicii.mds", "MecanicaHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/fizicianWS/services/Mecanica?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Mecanica.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/fizicianWS/services/Mecanica?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Mecanica(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Mecanica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Mecanica() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Mecanica(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Mecanica(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Mecanica(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpSoap11Endpoint")
    public MecanicaPortType getMecanicaHttpSoap11Endpoint() {
        return super.getPort(MecanicaHttpSoap11Endpoint, MecanicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpSoap11Endpoint")
    public MecanicaPortType getMecanicaHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(MecanicaHttpSoap11Endpoint, MecanicaPortType.class, features);
    }


    /**
     *
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpEndpoint")
    public MecanicaPortType getMecanicaHttpEndpoint() {
        return super.getPort(MecanicaHttpEndpoint, MecanicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpEndpoint")
    public MecanicaPortType getMecanicaHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(MecanicaHttpEndpoint, MecanicaPortType.class, features);
    }


    /**
     *
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpSoap12Endpoint")
    public MecanicaPortType getMecanicaHttpSoap12Endpoint() {
        return super.getPort(MecanicaHttpSoap12Endpoint, MecanicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MecanicaPortType
     */
    @WebEndpoint(name = "MecanicaHttpSoap12Endpoint")
    public MecanicaPortType getMecanicaHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(MecanicaHttpSoap12Endpoint, MecanicaPortType.class, features);
    }

}
