package mds.servicii;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-30T23:02:57.688+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://servicii.mds", name = "TermoDinamicaPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TermoDinamicaPortType {

    @WebMethod(action = "urn:moli")
    @Action(input = "urn:moli", output = "urn:moliResponse")
    @RequestWrapper(localName = "moli", targetNamespace = "http://servicii.mds", className = "mds.servicii.Moli")
    @ResponseWrapper(localName = "moliResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.MoliResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double moli(
        @WebParam(name = "m", targetNamespace = "http://servicii.mds")
        double m,
        @WebParam(name = "miu", targetNamespace = "http://servicii.mds")
        double miu
    );

    @WebMethod(action = "urn:presiune")
    @Action(input = "urn:presiune", output = "urn:presiuneResponse")
    @RequestWrapper(localName = "presiune", targetNamespace = "http://servicii.mds", className = "mds.servicii.Presiune")
    @ResponseWrapper(localName = "presiuneResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.PresiuneResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double presiune(
        @WebParam(name = "n", targetNamespace = "http://servicii.mds")
        double n,
        @WebParam(name = "m", targetNamespace = "http://servicii.mds")
        double m,
        @WebParam(name = "v", targetNamespace = "http://servicii.mds")
        double v
    );

    @WebMethod(operationName = "gaz_ideal", action = "urn:gaz_ideal")
    @Action(input = "urn:gaz_ideal", output = "urn:gaz_idealResponse")
    @RequestWrapper(localName = "gaz_ideal", targetNamespace = "http://servicii.mds", className = "mds.servicii.GazIdeal")
    @ResponseWrapper(localName = "gaz_idealResponse", targetNamespace = "http://servicii.mds", className = "mds.servicii.GazIdealResponse")
    @WebResult(name = "return", targetNamespace = "http://servicii.mds")
    public double gazIdeal(
        @WebParam(name = "n", targetNamespace = "http://servicii.mds")
        double n,
        @WebParam(name = "k", targetNamespace = "http://servicii.mds")
        double k,
        @WebParam(name = "t", targetNamespace = "http://servicii.mds")
        double t
    );
}
