package mds.servicii;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-30T23:02:57.716+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "TermoDinamica", 
                  wsdlLocation = "http://localhost:8081/fizicianWS/services/TermoDinamica?wsdl",
                  targetNamespace = "http://servicii.mds") 
public class TermoDinamica extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicii.mds", "TermoDinamica");
    public final static QName TermoDinamicaHttpEndpoint = new QName("http://servicii.mds", "TermoDinamicaHttpEndpoint");
    public final static QName TermoDinamicaHttpSoap12Endpoint = new QName("http://servicii.mds", "TermoDinamicaHttpSoap12Endpoint");
    public final static QName TermoDinamicaHttpSoap11Endpoint = new QName("http://servicii.mds", "TermoDinamicaHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/fizicianWS/services/TermoDinamica?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TermoDinamica.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/fizicianWS/services/TermoDinamica?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TermoDinamica(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TermoDinamica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TermoDinamica() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TermoDinamica(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TermoDinamica(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TermoDinamica(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpEndpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpEndpoint() {
        return super.getPort(TermoDinamicaHttpEndpoint, TermoDinamicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpEndpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(TermoDinamicaHttpEndpoint, TermoDinamicaPortType.class, features);
    }


    /**
     *
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpSoap12Endpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpSoap12Endpoint() {
        return super.getPort(TermoDinamicaHttpSoap12Endpoint, TermoDinamicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpSoap12Endpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(TermoDinamicaHttpSoap12Endpoint, TermoDinamicaPortType.class, features);
    }


    /**
     *
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpSoap11Endpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpSoap11Endpoint() {
        return super.getPort(TermoDinamicaHttpSoap11Endpoint, TermoDinamicaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TermoDinamicaPortType
     */
    @WebEndpoint(name = "TermoDinamicaHttpSoap11Endpoint")
    public TermoDinamicaPortType getTermoDinamicaHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(TermoDinamicaHttpSoap11Endpoint, TermoDinamicaPortType.class, features);
    }

}
